// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WxkBc3SjdpmpBYLRo0Pnf7eQjBZ1uR4',
    appId: '1:84771592082:android:18954e4e192e1d8b4f534b',
    messagingSenderId: '84771592082',
    projectId: 'charmai-39863',
    storageBucket: 'charmai-39863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBXGoNBTxmtJYHpx85vTR-p-dL8UGjnlk',
    appId: '1:84771592082:ios:3b5998822ee08c654f534b',
    messagingSenderId: '84771592082',
    projectId: 'charmai-39863',
    storageBucket: 'charmai-39863.firebasestorage.app',
    iosBundleId: 'com.skapps.charmAI',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWi8qskfFzuuDEB7Nn6KguJUPSgCVJPo',
    appId: '1:84771592082:web:f109363f84fbe2eb4f534b',
    messagingSenderId: '84771592082',
    projectId: 'charmai-39863',
    authDomain: 'charmai-39863.firebaseapp.com',
    storageBucket: 'charmai-39863.firebasestorage.app',
    measurementId: 'G-1SVYW117NX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBXGoNBTxmtJYHpx85vTR-p-dL8UGjnlk',
    appId: '1:84771592082:ios:19703b01e7f293e34f534b',
    messagingSenderId: '84771592082',
    projectId: 'charmai-39863',
    storageBucket: 'charmai-39863.firebasestorage.app',
    iosBundleId: 'com.example.charmAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwWi8qskfFzuuDEB7Nn6KguJUPSgCVJPo',
    appId: '1:84771592082:web:76db990bbb732aac4f534b',
    messagingSenderId: '84771592082',
    projectId: 'charmai-39863',
    authDomain: 'charmai-39863.firebaseapp.com',
    storageBucket: 'charmai-39863.firebasestorage.app',
    measurementId: 'G-NXKWNTSXT4',
  );

}